# Repo: codefoco/AzureDevopsTemplates
resources:
  repositories:
    - repository: templates
      type: github
      name: codefoco/AzureDevopsTemplates
      endpoint: codefoco

pool:
  vmImage: 'macOS-10.14'
  demands: msbuild

steps:
- checkout: self

- task: TriggerBuild@3
  displayName: 'Trigger a new build of NLua.Windows'
  inputs:
    buildDefinition: 'TestBuild.Foo'
    ignoreSslCertificateErrors: true
    useSameSourceVersion: true
    password: '$(myToken)'


- template: common-dotnet.yml@templates
- template: common-macos.yml@templates

